tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-secondary-fixed-variant": "#414754",
              "surface-container-lowest": "#ffffff",
              "tertiary-fixed-dim": "#fab896",
              "on-tertiary": "#ffffff",
              "inverse-primary": "#95d1ce",
              "inverse-surface": "#2e3132",
              "tertiary-fixed": "#ffdbcb",
              "outline": "#707978",
              "primary-fixed-dim": "#95d1ce",
              "on-primary-container": "#7ebab7",
              "surface-bright": "#f8fafb",
              "outline-variant": "#bfc8c7",
              "error": "#ba1a1a",
              "surface-container": "#eceeef",
              "secondary-container": "#dde2f3",
              "primary-fixed": "#b1eeea",
              "on-error-container": "#93000a",
              "surface-container-high": "#e6e8e9",
              "inverse-on-surface": "#eff1f2",
              "on-surface": "#191c1d",
              "background": "#f8fafb",
              "on-tertiary-container": "#e1a181",
              "on-secondary": "#ffffff",
              "on-tertiary-fixed": "#341100",
              "on-error": "#ffffff",
              "on-primary": "#ffffff",
              "primary": "#003331",
              "tertiary": "#49220a",
              "on-secondary-container": "#5e6473",
              "surface-container-highest": "#e1e3e4",
              "secondary-fixed-dim": "#c1c6d7",
              "on-background": "#191c1d",
              "on-surface-variant": "#3f4948",
              "surface-tint": "#2a6865",
              "surface-variant": "#e1e3e4",
              "tertiary-container": "#64371e",
              "on-tertiary-fixed-variant": "#693b22",
              "secondary": "#585e6c",
              "secondary-fixed": "#dde2f3",
              "surface-dim": "#d8dadb",
              "primary-container": "#004b49",
              "on-primary-fixed-variant": "#084f4d",
              "surface": "#f8fafb",
              "surface-container-low": "#f2f4f5",
              "on-primary-fixed": "#00201f",
              "error-container": "#ffdad6",
              "on-secondary-fixed": "#161c27"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Manrope"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      }