tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "primary": "#0056c3",
              "tertiary-fixed-dim": "#ffb3af",
              "tertiary-fixed": "#ffdad7",
              "on-primary-container": "#fefcff",
              "primary-fixed": "#d9e2ff",
              "inverse-on-surface": "#f2f0f0",
              "surface": "#faf9f9",
              "on-background": "#1b1c1c",
              "secondary": "#715c00",
              "inverse-surface": "#303031",
              "outline-variant": "#c2c6d6",
              "on-secondary": "#ffffff",
              "background": "#faf9f9",
              "tertiary": "#af262d",
              "surface-dim": "#dbdad9",
              "secondary-fixed-dim": "#ecc300",
              "secondary-container": "#ffd319",
              "surface-variant": "#e3e2e2",
              "on-secondary-fixed-variant": "#554500",
              "inverse-primary": "#afc6ff",
              "on-tertiary-fixed": "#410005",
              "primary-fixed-dim": "#afc6ff",
              "on-secondary-container": "#705b00",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed": "#ffe17a",
              "surface-container-high": "#e9e8e8",
              "on-secondary-fixed": "#231b00",
              "on-primary": "#ffffff",
              "surface-container": "#efeded",
              "on-tertiary-container": "#fffbff",
              "tertiary-container": "#d14043",
              "on-tertiary": "#ffffff",
              "on-primary-fixed-variant": "#004299",
              "outline": "#727786",
              "surface-tint": "#0059c8",
              "on-primary-fixed": "#001944",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#900b1b",
              "on-surface": "#1b1c1c",
              "on-error": "#ffffff",
              "surface-container-highest": "#e3e2e2",
              "surface-container-low": "#f5f3f3",
              "surface-bright": "#faf9f9",
              "error": "#ba1a1a",
              "primary-container": "#1f6feb",
              "on-surface-variant": "#424754",
              "on-error-container": "#93000a"
            },
            fontFamily: {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      }